from __future__ import annotations


LINES = {
    "red": {"id": "red", "name": "Red Line", "color": "#ff5c6a"},
    "green": {"id": "green", "name": "Green Line", "color": "#37d47a"},
    "aqua": {"id": "aqua", "name": "Aqua Connector", "color": "#46c7ff"},
    "transfer": {"id": "transfer", "name": "Transfer Link", "color": "#c9d4ff"},
}


STATIONS = [
    {
        "id": "iceri-seher",
        "name": "İçərişəhər",
        "line": "red",
        "x": 120,
        "y": 250,
        "base_passengers": 260,
        "max_capacity": 900,
        "tags": ["event"],
    },
    {
        "id": "sahil",
        "name": "Sahil",
        "line": "red",
        "x": 210,
        "y": 250,
        "base_passengers": 480,
        "max_capacity": 1400,
        "tags": ["event"],
    },
    {
        "id": "may28",
        "name": "28 May",
        "line": "red",
        "x": 320,
        "y": 250,
        "base_passengers": 860,
        "max_capacity": 2200,
        "tags": ["hub", "transfer", "event"],
    },
    {
        "id": "ganclik",
        "name": "Gənclik",
        "line": "red",
        "x": 430,
        "y": 210,
        "base_passengers": 660,
        "max_capacity": 1700,
        "tags": ["event"],
    },
    {
        "id": "narimanov",
        "name": "Nəriman Nərimanov",
        "line": "red",
        "x": 560,
        "y": 170,
        "base_passengers": 590,
        "max_capacity": 1500,
        "tags": ["hub"],
    },
    {
        "id": "koroglu",
        "name": "Koroğlu",
        "line": "red",
        "x": 700,
        "y": 170,
        "base_passengers": 720,
        "max_capacity": 1900,
        "tags": ["event", "hub"],
    },
    {
        "id": "ulduz",
        "name": "Ulduz",
        "line": "red",
        "x": 820,
        "y": 170,
        "base_passengers": 320,
        "max_capacity": 1000,
        "tags": [],
    },
    {
        "id": "twenty-yanvar",
        "name": "20 Yanvar",
        "line": "green",
        "x": 150,
        "y": 410,
        "base_passengers": 520,
        "max_capacity": 1300,
        "tags": [],
    },
    {
        "id": "inshaatcilar",
        "name": "İnşaatçılar",
        "line": "green",
        "x": 250,
        "y": 360,
        "base_passengers": 470,
        "max_capacity": 1200,
        "tags": [],
    },
    {
        "id": "memar-ecemi",
        "name": "Memar Əcəmi",
        "line": "green",
        "x": 380,
        "y": 380,
        "base_passengers": 600,
        "max_capacity": 1600,
        "tags": ["transfer", "hub"],
    },
    {
        "id": "nizami",
        "name": "Nizami",
        "line": "green",
        "x": 280,
        "y": 300,
        "base_passengers": 540,
        "max_capacity": 1500,
        "tags": [],
    },
    {
        "id": "jafar-jabbarli",
        "name": "Cəfər Cabbarlı",
        "line": "green",
        "x": 360,
        "y": 250,
        "base_passengers": 780,
        "max_capacity": 2100,
        "tags": ["hub", "transfer"],
    },
    {
        "id": "khatai",
        "name": "Xətai",
        "line": "green",
        "x": 500,
        "y": 270,
        "base_passengers": 460,
        "max_capacity": 1400,
        "tags": [],
    },
    {
        "id": "ahmedli",
        "name": "Əhmədli",
        "line": "green",
        "x": 640,
        "y": 320,
        "base_passengers": 620,
        "max_capacity": 1500,
        "tags": [],
    },
    {
        "id": "hazi-aslanov",
        "name": "Həzi Aslanov",
        "line": "green",
        "x": 770,
        "y": 360,
        "base_passengers": 710,
        "max_capacity": 1800,
        "tags": ["hub"],
    },
    {
        "id": "eight-noyabr",
        "name": "8 Noyabr",
        "line": "aqua",
        "x": 500,
        "y": 430,
        "base_passengers": 430,
        "max_capacity": 1300,
        "tags": [],
    },
    {
        "id": "avtovagzal",
        "name": "Avtovağzal",
        "line": "aqua",
        "x": 620,
        "y": 470,
        "base_passengers": 520,
        "max_capacity": 1500,
        "tags": ["hub"],
    },
]


SEGMENTS = [
    {"id": "red-1", "from": "iceri-seher", "to": "sahil", "line": "red", "kind": "rail"},
    {"id": "red-2", "from": "sahil", "to": "may28", "line": "red", "kind": "rail"},
    {"id": "red-3", "from": "may28", "to": "ganclik", "line": "red", "kind": "rail"},
    {"id": "red-4", "from": "ganclik", "to": "narimanov", "line": "red", "kind": "rail"},
    {"id": "red-5", "from": "narimanov", "to": "koroglu", "line": "red", "kind": "rail"},
    {"id": "red-6", "from": "koroglu", "to": "ulduz", "line": "red", "kind": "rail"},
    {"id": "green-1", "from": "twenty-yanvar", "to": "inshaatcilar", "line": "green", "kind": "rail"},
    {"id": "green-2", "from": "inshaatcilar", "to": "memar-ecemi", "line": "green", "kind": "rail"},
    {"id": "green-3", "from": "memar-ecemi", "to": "nizami", "line": "green", "kind": "rail"},
    {"id": "green-4", "from": "nizami", "to": "jafar-jabbarli", "line": "green", "kind": "rail"},
    {"id": "green-5", "from": "jafar-jabbarli", "to": "khatai", "line": "green", "kind": "rail"},
    {"id": "green-6", "from": "khatai", "to": "ahmedli", "line": "green", "kind": "rail"},
    {"id": "green-7", "from": "ahmedli", "to": "hazi-aslanov", "line": "green", "kind": "rail"},
    {"id": "aqua-1", "from": "memar-ecemi", "to": "eight-noyabr", "line": "aqua", "kind": "rail"},
    {"id": "aqua-2", "from": "eight-noyabr", "to": "avtovagzal", "line": "aqua", "kind": "rail"},
    {
        "id": "transfer-1",
        "from": "may28",
        "to": "jafar-jabbarli",
        "line": "transfer",
        "kind": "transfer",
    },
]


TRAINS = [
    {
        "id": "RT-01",
        "line": "red",
        "route": ["iceri-seher", "sahil", "may28", "ganclik", "narimanov", "koroglu", "ulduz"],
        "offset": 0.03,
        "speed": 1.0,
        "base_load": 310,
    },
    {
        "id": "RT-02",
        "line": "red",
        "route": ["iceri-seher", "sahil", "may28", "ganclik", "narimanov", "koroglu", "ulduz"],
        "offset": 0.38,
        "speed": 1.0,
        "base_load": 285,
    },
    {
        "id": "RT-03",
        "line": "red",
        "route": ["iceri-seher", "sahil", "may28", "ganclik", "narimanov", "koroglu", "ulduz"],
        "offset": 0.71,
        "speed": 1.0,
        "base_load": 340,
    },
    {
        "id": "GT-01",
        "line": "green",
        "route": [
            "twenty-yanvar",
            "inshaatcilar",
            "memar-ecemi",
            "nizami",
            "jafar-jabbarli",
            "khatai",
            "ahmedli",
            "hazi-aslanov",
        ],
        "offset": 0.18,
        "speed": 1.0,
        "base_load": 300,
    },
    {
        "id": "GT-02",
        "line": "green",
        "route": [
            "twenty-yanvar",
            "inshaatcilar",
            "memar-ecemi",
            "nizami",
            "jafar-jabbarli",
            "khatai",
            "ahmedli",
            "hazi-aslanov",
        ],
        "offset": 0.56,
        "speed": 1.0,
        "base_load": 320,
    },
    {
        "id": "AT-01",
        "line": "aqua",
        "route": ["memar-ecemi", "eight-noyabr", "avtovagzal"],
        "offset": 0.12,
        "speed": 1.0,
        "base_load": 190,
    },
    {
        "id": "AT-02",
        "line": "aqua",
        "route": ["memar-ecemi", "eight-noyabr", "avtovagzal"],
        "offset": 0.62,
        "speed": 1.0,
        "base_load": 205,
    },
]


DEFAULT_EVENT_STATIONS = ["koroglu", "ganclik", "sahil", "iceri-seher", "may28"]


SCENARIOS = {
    "normal": {
        "id": "normal",
        "label": "Normal Operation",
        "summary": "Balanced headways, moderate demand, and stable crowding.",
        "public_enabled": True,
        "station_multiplier": 1.0,
        "hub_multiplier": 1.08,
        "transfer_multiplier": 1.12,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.0,
        "speed_factor": 1.0,
        "dwell_factor": 1.0,
        "capacity_factor": 1.0,
        "delay_minutes": 4,
        "severity": "info",
    },
    "rush-hour": {
        "id": "rush-hour",
        "label": "Rush Hour Overload",
        "summary": "Demand spikes on hubs and transfer stations; dwell times stretch.",
        "public_enabled": True,
        "station_multiplier": 1.22,
        "hub_multiplier": 1.45,
        "transfer_multiplier": 1.55,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.12,
        "speed_factor": 0.93,
        "dwell_factor": 1.35,
        "capacity_factor": 1.0,
        "delay_minutes": 12,
        "severity": "warning",
    },
    "event-surge": {
        "id": "event-surge",
        "label": "Large Event Surge",
        "summary": "Pre- and post-event crowd waves build around destination stations.",
        "public_enabled": True,
        "station_multiplier": 1.06,
        "hub_multiplier": 1.18,
        "transfer_multiplier": 1.24,
        "event_multiplier": 1.9,
        "event_station_ids": DEFAULT_EVENT_STATIONS,
        "affected_station_multiplier": 1.22,
        "speed_factor": 0.95,
        "dwell_factor": 1.22,
        "capacity_factor": 1.0,
        "delay_minutes": 10,
        "severity": "warning",
    },
    "electricity-failure": {
        "id": "electricity-failure",
        "label": "Electricity Failure",
        "summary": "A power issue restricts a segment and forces systemwide slowdown.",
        "public_enabled": False,
        "station_multiplier": 1.12,
        "hub_multiplier": 1.36,
        "transfer_multiplier": 1.4,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.34,
        "speed_factor": 0.48,
        "dwell_factor": 1.7,
        "capacity_factor": 0.95,
        "delay_minutes": 26,
        "severity": "critical",
    },
    "train-breakdown": {
        "id": "train-breakdown",
        "label": "Train Breakdown",
        "summary": "One train is immobilized, delaying following services and platforms.",
        "public_enabled": False,
        "station_multiplier": 1.08,
        "hub_multiplier": 1.28,
        "transfer_multiplier": 1.25,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.3,
        "speed_factor": 0.72,
        "dwell_factor": 1.45,
        "capacity_factor": 1.0,
        "delay_minutes": 18,
        "severity": "critical",
    },
    "track-intrusion": {
        "id": "track-intrusion",
        "label": "Track Intrusion",
        "summary": "Immediate operational stop near the incident zone and passenger redirection.",
        "public_enabled": False,
        "station_multiplier": 1.1,
        "hub_multiplier": 1.32,
        "transfer_multiplier": 1.3,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.4,
        "speed_factor": 0.22,
        "dwell_factor": 1.9,
        "capacity_factor": 0.92,
        "delay_minutes": 32,
        "severity": "critical",
    },
    "ventilation-failure": {
        "id": "ventilation-failure",
        "label": "Ventilation Failure",
        "summary": "Station entry is restricted as the local safe capacity drops sharply.",
        "public_enabled": False,
        "station_multiplier": 1.04,
        "hub_multiplier": 1.14,
        "transfer_multiplier": 1.18,
        "event_multiplier": 1.0,
        "event_station_ids": [],
        "affected_station_multiplier": 1.2,
        "speed_factor": 0.92,
        "dwell_factor": 1.2,
        "capacity_factor": 0.58,
        "delay_minutes": 14,
        "severity": "critical",
    },
}


DEMO_USERS = [
    {
        "name": "Leyla Commuter",
        "email": "commuter@nexusmetro.local",
        "password": "Metro123!",
        "role": "user",
        "is_active": True,
    },
    {
        "name": "Rashad Ops",
        "email": "staff.ops@nexusmetro.local",
        "password": "Metro123!",
        "role": "staff",
        "is_active": True,
    },
    {
        "name": "Nigar Admin",
        "email": "admin@nexusmetro.local",
        "password": "Admin123!",
        "role": "admin",
        "is_active": True,
    },
]


STARTER_ALERTS = [
    {
        "title": "MetroTwin Demo Live",
        "message": "Simulation feed is running. Switch scenarios to see crowd and service changes in real time.",
        "severity": "info",
        "target_role": "public",
        "created_by": "system",
    }
]

